//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int SenderAccountId { get; set; }
        public int RecipientAccountId { get; set; }
        public long Amount { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Committed { get; set; }
    
        public virtual Account RecipientAccount { get; set; }
        public virtual Account SenderAccount { get; set; }
    }
}
